import type { TemplateDefinition } from "./types.js";

const sans = 'system-ui, -apple-system, "SF Pro Display", "Helvetica Neue", sans-serif';
const sansText = 'system-ui, -apple-system, "SF Pro Text", "Helvetica Neue", sans-serif';
const rounded = 'system-ui, -apple-system, "SF Pro Rounded", "Helvetica Neue", sans-serif';
const inter = '"Inter", system-ui, -apple-system, "Segoe UI", sans-serif';
const serif = 'Georgia, "Iowan Old Style", "Palatino Linotype", serif';
const mono =
  'ui-monospace, "SF Mono", "Menlo", "Consolas", monospace';

export const TEMPLATE_CATALOG: TemplateDefinition[] = [
  {
    id: "utility-clean",
    label: "Utility Clean",
    category: "utility",
    description: "Bright, centred hero for everyday productivity apps.",
    typography: {
      headlineFontFamily: sans,
      headlineWeight: 800,
      headlineSizeRatio: 0.078,
      headlineLineHeight: 1.05,
      headlineLetterSpacing: -0.02,
      subheadFontFamily: sansText,
      subheadWeight: 500,
      subheadSizeRatio: 0.034,
      subheadLineHeight: 1.35,
      subheadOpacity: 0.72,
      headlineColor: "#0F172A",
      subheadColor: "#334155",
      featureTitleSizeRatio: 0.032,
      featureBodySizeRatio: 0.026,
    },
    layout: {
      paddingXRatio: 0.08,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.84,
      subheadMaxWidthDefault: 0.78,
      featureListStartRatio: 0.42,
      featureCardsYRatio: 0.58,
    },
    featureCards: {
      fill: "#FFFFFF",
      fillOpacity: 0.92,
      borderRadius: 16,
      titleColor: "#0F172A",
      subtitleColor: "#475569",
    },
    headlineTopRatio: 0.09,
    subheadGapRatio: 0.028,
    deviceDefaultScale: 0.82,
    decorativeIntensity: "minimal",
    decorStyle: "soft-orbs",
    starter: {
      backgroundPreset: "soft-blue",
      device: { scale: 0.82, x: 0.5, y: 0.73, appearance: "dark" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
  {
    id: "utility-minimal",
    label: "Utility Minimal",
    category: "utility",
    description: "Left-aligned type on a quiet white canvas.",
    typography: {
      headlineFontFamily: inter,
      headlineWeight: 700,
      headlineSizeRatio: 0.066,
      headlineLineHeight: 1.12,
      headlineLetterSpacing: -0.015,
      subheadFontFamily: inter,
      subheadWeight: 400,
      subheadSizeRatio: 0.03,
      subheadLineHeight: 1.45,
      subheadOpacity: 0.65,
      headlineColor: "#18181B",
      subheadColor: "#52525B",
      featureTitleSizeRatio: 0.03,
      featureBodySizeRatio: 0.024,
    },
    layout: {
      paddingXRatio: 0.1,
      defaultTextAlign: "left",
      headlineMaxWidthDefault: 0.72,
      subheadMaxWidthDefault: 0.68,
      featureListStartRatio: 0.38,
      featureCardsYRatio: 0.56,
    },
    featureCards: {
      fill: "#F4F4F5",
      fillOpacity: 1,
      borderRadius: 12,
      titleColor: "#18181B",
      subtitleColor: "#71717A",
    },
    headlineTopRatio: 0.1,
    subheadGapRatio: 0.032,
    deviceDefaultScale: 0.78,
    decorativeIntensity: "minimal",
    decorStyle: "none",
    starter: {
      backgroundPreset: "clean-white",
      device: { scale: 0.78, x: 0.62, y: 0.74, appearance: "light" },
      layout: { type: "hero-device", textAlign: "left" },
    },
  },
  {
    id: "utility-pro",
    label: "Utility Pro",
    category: "utility",
    description: "Dark slate styling for finance, dev tools, and B2B apps.",
    typography: {
      headlineFontFamily: inter,
      headlineWeight: 700,
      headlineSizeRatio: 0.072,
      headlineLineHeight: 1.08,
      headlineLetterSpacing: -0.01,
      subheadFontFamily: inter,
      subheadWeight: 500,
      subheadSizeRatio: 0.031,
      subheadLineHeight: 1.4,
      subheadOpacity: 0.8,
      headlineColor: "#F8FAFC",
      subheadColor: "#CBD5E1",
      featureTitleSizeRatio: 0.031,
      featureBodySizeRatio: 0.025,
    },
    layout: {
      paddingXRatio: 0.09,
      defaultTextAlign: "left",
      headlineMaxWidthDefault: 0.8,
      subheadMaxWidthDefault: 0.74,
      featureListStartRatio: 0.4,
      featureCardsYRatio: 0.57,
    },
    featureCards: {
      fill: "#1E293B",
      fillOpacity: 0.92,
      borderRadius: 14,
      titleColor: "#F1F5F9",
      subtitleColor: "#94A3B8",
    },
    headlineTopRatio: 0.085,
    subheadGapRatio: 0.026,
    deviceDefaultScale: 0.8,
    decorativeIntensity: "minimal",
    decorStyle: "corner-wash",
    starter: {
      backgroundPreset: "slate-pro",
      device: { scale: 0.8, x: 0.58, y: 0.72, appearance: "light" },
      layout: { type: "hero-device", textAlign: "left" },
    },
  },
  {
    id: "utility-editorial",
    label: "Utility Editorial",
    category: "utility",
    description: "Serif headlines and warm paper tones for reading apps.",
    typography: {
      headlineFontFamily: serif,
      headlineWeight: 700,
      headlineSizeRatio: 0.082,
      headlineLineHeight: 1.06,
      headlineLetterSpacing: -0.01,
      subheadFontFamily: sansText,
      subheadWeight: 500,
      subheadSizeRatio: 0.033,
      subheadLineHeight: 1.42,
      subheadOpacity: 0.78,
      headlineColor: "#292524",
      subheadColor: "#57534E",
      featureTitleSizeRatio: 0.032,
      featureBodySizeRatio: 0.026,
    },
    layout: {
      paddingXRatio: 0.09,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.82,
      subheadMaxWidthDefault: 0.76,
      featureListStartRatio: 0.41,
      featureCardsYRatio: 0.58,
    },
    featureCards: {
      fill: "#FFFBEB",
      fillOpacity: 0.95,
      borderRadius: 8,
      titleColor: "#292524",
      subtitleColor: "#78716C",
    },
    headlineTopRatio: 0.095,
    subheadGapRatio: 0.03,
    deviceDefaultScale: 0.79,
    decorativeIntensity: "minimal",
    decorStyle: "corner-wash",
    starter: {
      backgroundPreset: "warm-cream",
      device: { scale: 0.79, x: 0.5, y: 0.74, appearance: "light" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
  {
    id: "utility-mint",
    label: "Utility Mint",
    category: "utility",
    description: "Fresh green gradients for health and wellness utilities.",
    typography: {
      headlineFontFamily: rounded,
      headlineWeight: 800,
      headlineSizeRatio: 0.076,
      headlineLineHeight: 1.06,
      headlineLetterSpacing: -0.015,
      subheadFontFamily: sansText,
      subheadWeight: 500,
      subheadSizeRatio: 0.033,
      subheadLineHeight: 1.38,
      subheadOpacity: 0.75,
      headlineColor: "#064E3B",
      subheadColor: "#047857",
      featureTitleSizeRatio: 0.031,
      featureBodySizeRatio: 0.025,
    },
    layout: {
      paddingXRatio: 0.08,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.84,
      subheadMaxWidthDefault: 0.78,
      featureListStartRatio: 0.42,
      featureCardsYRatio: 0.58,
    },
    featureCards: {
      fill: "#FFFFFF",
      fillOpacity: 0.9,
      borderRadius: 20,
      titleColor: "#065F46",
      subtitleColor: "#059669",
    },
    headlineTopRatio: 0.088,
    subheadGapRatio: 0.027,
    deviceDefaultScale: 0.81,
    decorativeIntensity: "medium",
    decorStyle: "wave-lines",
    starter: {
      backgroundPreset: "mint-fresh",
      device: { scale: 0.81, x: 0.5, y: 0.73, appearance: "dark" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
  {
    id: "puzzle",
    label: "Puzzle Classic",
    category: "puzzle",
    description: "Rounded type on deep purple — great for word and logic games.",
    typography: {
      headlineFontFamily: rounded,
      headlineWeight: 900,
      headlineSizeRatio: 0.088,
      headlineLineHeight: 1.02,
      headlineLetterSpacing: 0,
      subheadFontFamily: sansText,
      subheadWeight: 600,
      subheadSizeRatio: 0.036,
      subheadLineHeight: 1.3,
      subheadOpacity: 0.92,
      headlineColor: "#FFFFFF",
      subheadColor: "#F8FAFC",
      featureTitleSizeRatio: 0.034,
      featureBodySizeRatio: 0.028,
    },
    layout: {
      paddingXRatio: 0.08,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.86,
      subheadMaxWidthDefault: 0.8,
      featureListStartRatio: 0.4,
      featureCardsYRatio: 0.56,
    },
    featureCards: {
      fill: "#FFFFFF",
      fillOpacity: 0.15,
      borderRadius: 22,
      titleColor: "#FFFFFF",
      subtitleColor: "#E2E8F0",
    },
    headlineTopRatio: 0.078,
    subheadGapRatio: 0.022,
    deviceDefaultScale: 0.88,
    decorativeIntensity: "medium",
    decorStyle: "starfield",
    starter: {
      backgroundPreset: "dark-game",
      device: { scale: 0.88, x: 0.5, y: 0.72, appearance: "light" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
  {
    id: "puzzle-soft",
    label: "Puzzle Soft",
    category: "puzzle",
    description: "Pastel lavender with gentle bubbles for casual brain games.",
    typography: {
      headlineFontFamily: rounded,
      headlineWeight: 800,
      headlineSizeRatio: 0.08,
      headlineLineHeight: 1.04,
      headlineLetterSpacing: -0.005,
      subheadFontFamily: rounded,
      subheadWeight: 600,
      subheadSizeRatio: 0.035,
      subheadLineHeight: 1.32,
      subheadOpacity: 0.85,
      headlineColor: "#4C1D95",
      subheadColor: "#6D28D9",
      featureTitleSizeRatio: 0.033,
      featureBodySizeRatio: 0.027,
    },
    layout: {
      paddingXRatio: 0.085,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.85,
      subheadMaxWidthDefault: 0.8,
      featureListStartRatio: 0.41,
      featureCardsYRatio: 0.57,
    },
    featureCards: {
      fill: "#FFFFFF",
      fillOpacity: 0.88,
      borderRadius: 24,
      titleColor: "#5B21B6",
      subtitleColor: "#7C3AED",
    },
    headlineTopRatio: 0.086,
    subheadGapRatio: 0.025,
    deviceDefaultScale: 0.86,
    decorativeIntensity: "medium",
    decorStyle: "soft-orbs",
    starter: {
      backgroundPreset: "soft-lavender",
      device: { scale: 0.86, x: 0.5, y: 0.73, appearance: "dark" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
  {
    id: "puzzle-vivid",
    label: "Puzzle Vivid",
    category: "puzzle",
    description: "High-energy candy gradient for match‑3 and arcade puzzles.",
    typography: {
      headlineFontFamily: rounded,
      headlineWeight: 900,
      headlineSizeRatio: 0.092,
      headlineLineHeight: 0.98,
      headlineLetterSpacing: 0.01,
      subheadFontFamily: sansText,
      subheadWeight: 700,
      subheadSizeRatio: 0.037,
      subheadLineHeight: 1.22,
      subheadOpacity: 0.95,
      headlineColor: "#FFFFFF",
      subheadColor: "#FFF7ED",
      featureTitleSizeRatio: 0.035,
      featureBodySizeRatio: 0.028,
    },
    layout: {
      paddingXRatio: 0.075,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.88,
      subheadMaxWidthDefault: 0.82,
      featureListStartRatio: 0.39,
      featureCardsYRatio: 0.55,
    },
    featureCards: {
      fill: "#FFFFFF",
      fillOpacity: 0.25,
      borderRadius: 18,
      titleColor: "#FFFFFF",
      subtitleColor: "#FFEDD5",
    },
    headlineTopRatio: 0.072,
    subheadGapRatio: 0.02,
    deviceDefaultScale: 0.9,
    decorativeIntensity: "high",
    decorStyle: "glow-center",
    starter: {
      backgroundPreset: "candy-pop",
      device: { scale: 0.9, x: 0.5, y: 0.71, appearance: "light" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
  {
    id: "puzzle-night",
    label: "Puzzle Night",
    category: "puzzle",
    description: "Midnight blues with starfield decor for evening play.",
    typography: {
      headlineFontFamily: sans,
      headlineWeight: 800,
      headlineSizeRatio: 0.084,
      headlineLineHeight: 1.04,
      headlineLetterSpacing: -0.01,
      subheadFontFamily: sansText,
      subheadWeight: 500,
      subheadSizeRatio: 0.034,
      subheadLineHeight: 1.35,
      subheadOpacity: 0.88,
      headlineColor: "#E0F2FE",
      subheadColor: "#BAE6FD",
      featureTitleSizeRatio: 0.032,
      featureBodySizeRatio: 0.026,
    },
    layout: {
      paddingXRatio: 0.08,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.84,
      subheadMaxWidthDefault: 0.78,
      featureListStartRatio: 0.41,
      featureCardsYRatio: 0.57,
    },
    featureCards: {
      fill: "#0C4A6E",
      fillOpacity: 0.65,
      borderRadius: 16,
      titleColor: "#F0F9FF",
      subtitleColor: "#7DD3FC",
    },
    headlineTopRatio: 0.082,
    subheadGapRatio: 0.024,
    deviceDefaultScale: 0.85,
    decorativeIntensity: "medium",
    decorStyle: "starfield",
    starter: {
      backgroundPreset: "ocean-deep",
      device: { scale: 0.85, x: 0.5, y: 0.72, appearance: "light" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
  {
    id: "arcade",
    label: "Arcade Blast",
    category: "arcade",
    description: "Bold centred headlines on a vivid sunset gradient.",
    typography: {
      headlineFontFamily: sans,
      headlineWeight: 900,
      headlineSizeRatio: 0.094,
      headlineLineHeight: 0.98,
      headlineLetterSpacing: 0.025,
      subheadFontFamily: sansText,
      subheadWeight: 700,
      subheadSizeRatio: 0.036,
      subheadLineHeight: 1.2,
      subheadOpacity: 0.9,
      headlineColor: "#FFFFFF",
      subheadColor: "#FEF3C7",
      featureTitleSizeRatio: 0.034,
      featureBodySizeRatio: 0.027,
    },
    layout: {
      paddingXRatio: 0.07,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.9,
      subheadMaxWidthDefault: 0.84,
      featureListStartRatio: 0.38,
      featureCardsYRatio: 0.54,
    },
    featureCards: {
      fill: "#FFFFFF",
      fillOpacity: 0.2,
      borderRadius: 14,
      titleColor: "#FFFFFF",
      subtitleColor: "#FDE68A",
    },
    headlineTopRatio: 0.07,
    subheadGapRatio: 0.018,
    deviceDefaultScale: 0.92,
    decorativeIntensity: "high",
    decorStyle: "glow-center",
    starter: {
      backgroundPreset: "bright-game",
      device: { scale: 0.92, x: 0.5, y: 0.7, appearance: "light" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
  {
    id: "arcade-neon",
    label: "Arcade Neon",
    category: "arcade",
    description: "Cyber grid and monospace accents for fast action games.",
    typography: {
      headlineFontFamily: mono,
      headlineWeight: 800,
      headlineSizeRatio: 0.078,
      headlineLineHeight: 1.05,
      headlineLetterSpacing: 0.04,
      subheadFontFamily: sansText,
      subheadWeight: 600,
      subheadSizeRatio: 0.032,
      subheadLineHeight: 1.3,
      subheadOpacity: 0.88,
      headlineColor: "#22D3EE",
      subheadColor: "#E879F9",
      featureTitleSizeRatio: 0.03,
      featureBodySizeRatio: 0.024,
    },
    layout: {
      paddingXRatio: 0.08,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.88,
      subheadMaxWidthDefault: 0.82,
      featureListStartRatio: 0.39,
      featureCardsYRatio: 0.55,
    },
    featureCards: {
      fill: "#0F172A",
      fillOpacity: 0.85,
      borderRadius: 8,
      titleColor: "#22D3EE",
      subtitleColor: "#C084FC",
    },
    headlineTopRatio: 0.076,
    subheadGapRatio: 0.022,
    deviceDefaultScale: 0.9,
    decorativeIntensity: "high",
    decorStyle: "neon-grid",
    starter: {
      backgroundPreset: "neon-night",
      device: { scale: 0.9, x: 0.5, y: 0.71, appearance: "light" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
  {
    id: "arcade-retro",
    label: "Arcade Retro",
    category: "arcade",
    description: "Warm sunset bands with chunky type for retro platformers.",
    typography: {
      headlineFontFamily: rounded,
      headlineWeight: 900,
      headlineSizeRatio: 0.09,
      headlineLineHeight: 1,
      headlineLetterSpacing: 0.015,
      subheadFontFamily: rounded,
      subheadWeight: 700,
      subheadSizeRatio: 0.035,
      subheadLineHeight: 1.25,
      subheadOpacity: 0.9,
      headlineColor: "#FFF7ED",
      subheadColor: "#FED7AA",
      featureTitleSizeRatio: 0.033,
      featureBodySizeRatio: 0.027,
    },
    layout: {
      paddingXRatio: 0.075,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.88,
      subheadMaxWidthDefault: 0.82,
      featureListStartRatio: 0.4,
      featureCardsYRatio: 0.56,
    },
    featureCards: {
      fill: "#7C2D12",
      fillOpacity: 0.75,
      borderRadius: 10,
      titleColor: "#FFEDD5",
      subtitleColor: "#FDBA74",
    },
    headlineTopRatio: 0.074,
    subheadGapRatio: 0.02,
    deviceDefaultScale: 0.88,
    decorativeIntensity: "medium",
    decorStyle: "diagonal-bands",
    starter: {
      backgroundPreset: "sunset-warm",
      device: { scale: 0.88, x: 0.5, y: 0.72, appearance: "light" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
  {
    id: "arcade-candy",
    label: "Arcade Candy",
    category: "arcade",
    description: "Playful waves and coral tones for family-friendly arcade titles.",
    typography: {
      headlineFontFamily: rounded,
      headlineWeight: 900,
      headlineSizeRatio: 0.096,
      headlineLineHeight: 0.96,
      headlineLetterSpacing: 0.02,
      subheadFontFamily: rounded,
      subheadWeight: 700,
      subheadSizeRatio: 0.038,
      subheadLineHeight: 1.18,
      subheadOpacity: 0.92,
      headlineColor: "#FFFFFF",
      subheadColor: "#FFE4E6",
      featureTitleSizeRatio: 0.035,
      featureBodySizeRatio: 0.028,
    },
    layout: {
      paddingXRatio: 0.07,
      defaultTextAlign: "center",
      headlineMaxWidthDefault: 0.9,
      subheadMaxWidthDefault: 0.85,
      featureListStartRatio: 0.37,
      featureCardsYRatio: 0.53,
    },
    featureCards: {
      fill: "#FFFFFF",
      fillOpacity: 0.28,
      borderRadius: 26,
      titleColor: "#FFFFFF",
      subtitleColor: "#FECDD3",
    },
    headlineTopRatio: 0.068,
    subheadGapRatio: 0.016,
    deviceDefaultScale: 0.93,
    decorativeIntensity: "high",
    decorStyle: "wave-lines",
    starter: {
      backgroundPreset: "soft-coral",
      device: { scale: 0.93, x: 0.5, y: 0.69, appearance: "dark" },
      layout: { type: "hero-device", textAlign: "center" },
    },
  },
];
