import fs from "node:fs/promises";
import path from "node:path";
import { AppConfigSchema, type AppConfig } from "../schemas/app-config.js";
import { getProjectRoot, appRoot } from "./paths.js";
import {
  ensureAppConfigJson,
  readConfigObjectFromTsFile,
} from "./ensure-app-config-json.js";
import { importAppConfigModule } from "./load-app-config-file.js";

function jsonConfigPath(appId: string): string {
  return path.join(appRoot(appId), "app.config.json");
}

function tsConfigPath(appId: string): string {
  return path.join(appRoot(appId), "app.config.ts");
}

export async function listApps(): Promise<{ id: string; name: string }[]> {
  const appsDir = path.join(getProjectRoot(), "apps");
  try {
    const entries = await fs.readdir(appsDir, { withFileTypes: true });
    const apps: { id: string; name: string }[] = [];
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      try {
        const config = await loadAppConfig(e.name);
        apps.push({ id: config.app.id, name: config.app.name });
      } catch {
        /* skip invalid */
      }
    }
    return apps.sort((a, b) => a.name.localeCompare(b.name));
  } catch {
    return [];
  }
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

export async function loadAppConfig(appId: string): Promise<AppConfig> {
  const jsonPath = jsonConfigPath(appId);
  const tsPath = tsConfigPath(appId);
  const seedAppsRoot = process.env.STOREKIT_SEED_APPS_ROOT;

  if (process.env.STOREKIT_PACKAGED) {
    await ensureAppConfigJson(appId, { seedAppsRoot });
  } else if (!(await pathExists(jsonPath)) && (await pathExists(tsPath))) {
    const fromTs = await readConfigObjectFromTsFile(tsPath);
    const early = AppConfigSchema.safeParse(fromTs);
    if (early.success) {
      await fs.writeFile(jsonPath, JSON.stringify(early.data, null, 2), "utf-8");
    }
  }

  let raw: unknown;

  if (await pathExists(jsonPath)) {
    raw = JSON.parse(await fs.readFile(jsonPath, "utf-8"));
  } else if (process.env.STOREKIT_PACKAGED) {
    throw new Error(
      `App config not found: apps/${appId}/app.config.json. Use Cody1StoreKit → Open Apps Folder and ensure app.config.json exists, then restart the app.`,
    );
  } else if (await pathExists(tsPath)) {
    const mod = importAppConfigModule(tsPath) as {
      default?: unknown;
      config?: unknown;
    };
    raw = mod?.default ?? mod?.config ?? mod;
    const parsed = AppConfigSchema.safeParse(raw);
    if (parsed.success) {
      await fs.writeFile(jsonPath, JSON.stringify(parsed.data, null, 2), "utf-8");
    }
  } else {
    throw new Error(
      `App config not found: apps/${appId}/app.config.json (or app.config.ts)`,
    );
  }

  const parsed = AppConfigSchema.safeParse(raw);
  if (!parsed.success) {
    const msg = parsed.error.errors
      .map((e) => `${e.path.join(".")}: ${e.message}`)
      .join("\n");
    throw new Error(`Invalid app configuration for ${appId}:\n${msg}`);
  }
  return parsed.data;
}

export async function saveAppConfig(
  appId: string,
  config: AppConfig,
): Promise<void> {
  const validated = AppConfigSchema.parse(config);
  const jsonPath = jsonConfigPath(appId);
  await fs.writeFile(jsonPath, JSON.stringify(validated, null, 2), "utf-8");

  const tsPath = tsConfigPath(appId);
  const body = `/** Generated by Cody1StoreKit — prefer editing app.config.json in the UI. */\nexport default ${JSON.stringify(validated, null, 2)};\n`;
  await fs.writeFile(tsPath, body, "utf-8");
}
